// Auto-generated by Claude Code from Smith AI Agency Cockpit Google Sheet
// Spreadsheet: 1iZUsOKh1hAR0qtnu5HGk9WxTEXMuaZcvKY5pF0TVEJI
// Last sync: 2026-03-04T08:17:00Z

const DASHBOARD_DATA = {
  lastSync: "2026-03-04T08:17:00Z",
  overview: [
    { project: "CLIENT-001 Love Over Exile", rag: "Green", omtmName: "Email signups/week", omtmValue: 0, omtmTarget: 50, trend: "—", focus: "Content + GA4 setup" },
    { project: "CLIENT-002 Hairgenetix", rag: "Green", omtmName: "Organic clicks/month", omtmValue: 1385, omtmTarget: 2000, trend: "—", focus: "Content hub + SEO implementation" },
    { project: "PROD-001 SEO Toolkit", rag: "Green", omtmName: "Services at 80+/100", omtmValue: 3, omtmTarget: 5, trend: "up", focus: "AI Discovery v2 + Content service" },
    { project: "PROD-002 SellFunnel", rag: "Green", omtmName: "Research milestones", omtmValue: 1, omtmTarget: 4, trend: "—", focus: "Architecture strategy" },
    { project: "INFRA-003 Monitoring", rag: "Green", omtmName: "Dashboard pages live", omtmValue: 0, omtmTarget: 5, trend: "—", focus: "Build cockpit dashboard" },
    { project: "INFRA-004 Task Management", rag: "Green", omtmName: "Board active", omtmValue: 1, omtmTarget: 1, trend: "—", focus: "Maintain" }
  ],
  tasks: [
    { name: "Financial: Complete cost inventory checklist", project: "INFRA", status: "This Week", priority: "Medium", due: "", lastActivity: "2026-03-02", daysInStatus: 1, url: "https://trello.com/c/UZWj0sVZ" },
    { name: "INFRA-005: First research cycle — Claude Code best practices", project: "INFRA", status: "This Week", priority: "Medium", due: "", lastActivity: "2026-03-02", daysInStatus: 1, url: "https://trello.com/c/H0wdllLy" },
    { name: "LOE SITE-003: Generate site images (Imagen 4)", project: "LOE", status: "This Week", priority: "Medium", due: "", lastActivity: "2026-03-02", daysInStatus: 1, url: "https://trello.com/c/aHpfBBQT" },
    { name: "LOE: Fix SEO audit warnings (36 items)", project: "LOE", status: "This Week", priority: "Medium", due: "", lastActivity: "2026-03-02", daysInStatus: 1, url: "https://trello.com/c/g1sVP85U" },
    { name: "HG: Fix H1 tags + meta titles/descriptions (34 pages)", project: "Hairgenetix", status: "This Week", priority: "Medium", due: "", lastActivity: "2026-03-03", daysInStatus: 0, url: "https://trello.com/c/zVihksrx" },
    { name: "SEO-001: Create DataForSEO account + deposit $50", project: "SEO", status: "Blocked", priority: "Low", due: "", lastActivity: "2026-03-02", daysInStatus: 1, url: "https://trello.com/c/Pal98Bld" },
    { name: "SEO-003: Start SE Ranking 14-day free trial", project: "SEO", status: "Blocked", priority: "Low", due: "", lastActivity: "2026-03-02", daysInStatus: 1, url: "https://trello.com/c/xWosGhaB" },
    { name: "INFRA-001: Set up Overnight CLI Runner", project: "INFRA", status: "Backlog", priority: "Low", due: "", lastActivity: "2026-03-02", daysInStatus: 1, url: "https://trello.com/c/Hg0V0p37" },
    { name: "INFRA-002: Create Project Template Repo", project: "INFRA", status: "Backlog", priority: "Low", due: "", lastActivity: "2026-03-02", daysInStatus: 1, url: "https://trello.com/c/qpaWjSRZ" },
    { name: "INFRA-003: Set up BI Dashboard (Looker Studio + Sheets)", project: "INFRA", status: "Backlog", priority: "Low", due: "", lastActivity: "2026-03-02", daysInStatus: 1, url: "https://trello.com/c/V3G7QEBB" },
    { name: "INFRA-005: Set up knowledge base folder structure", project: "INFRA", status: "Backlog", priority: "Low", due: "", lastActivity: "2026-03-02", daysInStatus: 1, url: "https://trello.com/c/bIsd6Daz" },
    { name: "SF-001: SellFunnel architecture strategy", project: "SF", status: "Backlog", priority: "Low", due: "", lastActivity: "2026-03-02", daysInStatus: 1, url: "https://trello.com/c/E1bVnPJS" },
    { name: "TOOL-001: Fix Bitwarden CLI unlock", project: "INFRA", status: "Backlog", priority: "Low", due: "", lastActivity: "2026-03-02", daysInStatus: 1, url: "https://trello.com/c/W6pr3Md9" },
    { name: "TOOL-002: Set up Bitwarden vault structure", project: "INFRA", status: "Backlog", priority: "Low", due: "", lastActivity: "2026-03-02", daysInStatus: 1, url: "https://trello.com/c/vbbItYfl" },
    { name: "SEO-024: Schedule recurring SEO audits", project: "SEO", status: "Backlog", priority: "Low", due: "", lastActivity: "2026-03-02", daysInStatus: 1, url: "https://trello.com/c/NoIwEBzv" },
    { name: "SEO-025: Apply audit recommendations to LOE", project: "SEO", status: "Backlog", priority: "Low", due: "", lastActivity: "2026-03-02", daysInStatus: 1, url: "https://trello.com/c/983gPPot" },
    { name: "SEO-007: Connect SEMrush via Rube", project: "SEO", status: "Backlog", priority: "Low", due: "", lastActivity: "2026-03-02", daysInStatus: 1, url: "https://trello.com/c/afwNYpG5" },
    { name: "LOE: Malcolm — activate 3 MailerLite automations in UI", project: "LOE", status: "Backlog", priority: "Low", due: "", lastActivity: "2026-03-02", daysInStatus: 1, url: "https://trello.com/c/Pq5XyedR" },
    { name: "INFRA-004: Set up Trello board + migrate tasks", project: "INFRA", status: "Done", priority: "Low", due: "", lastActivity: "2026-03-02", daysInStatus: 1, url: "https://trello.com/c/ykRH92qT" },
    { name: "LOE SITE-004: Connect MailerLite forms", project: "LOE", status: "Done", priority: "Low", due: "", lastActivity: "2026-03-02", daysInStatus: 1, url: "https://trello.com/c/PczVO3lP" },
    { name: "LOE SITE-002: Set up Google Analytics 4", project: "LOE", status: "Done", priority: "Low", due: "", lastActivity: "2026-03-02", daysInStatus: 1, url: "https://trello.com/c/aPvTaCH5" },
    { name: "LOE SITE-006: DNS cutover to Vercel (GoDaddy)", project: "LOE", status: "Done", priority: "Low", due: "", lastActivity: "2026-03-02", daysInStatus: 1, url: "https://trello.com/c/y7YmNl2C" },
    { name: "SEO-012: Content Optimizer service built", project: "SEO", status: "Done", priority: "Low", due: "", lastActivity: "2026-03-02", daysInStatus: 1, url: "https://trello.com/c/GnqmH3GY" },
    { name: "CLIENT-002: Hairgenetix — initial setup + first SEO audit", project: "Hairgenetix", status: "Done", priority: "Low", due: "", lastActivity: "2026-03-03", daysInStatus: 0, url: "https://trello.com/c/ozxhDug4" },
    { name: "SEO-013: AI Discovery Audit service built", project: "SEO", status: "Done", priority: "Low", due: "", lastActivity: "2026-03-02", daysInStatus: 1, url: "https://trello.com/c/t1IARwQX" },
    { name: "SEO-010: Build Audit Agent", project: "SEO", status: "Done", priority: "Low", due: "", lastActivity: "2026-03-02", daysInStatus: 1, url: "https://trello.com/c/c7SvuUcm" },
    { name: "SEO-011: Build Keywords Agent", project: "SEO", status: "Done", priority: "Low", due: "", lastActivity: "2026-03-02", daysInStatus: 1, url: "https://trello.com/c/HcZEcGTl" },
    { name: "SEO-002: Google Search Console connected", project: "SEO", status: "Done", priority: "Low", due: "", lastActivity: "2026-03-02", daysInStatus: 1, url: "https://trello.com/c/tKCrmNUh" },
    { name: "LOE WP-005: Write and publish real content", project: "LOE", status: "Done", priority: "Low", due: "", lastActivity: "2026-03-02", daysInStatus: 1, url: "https://trello.com/c/PTNGbAQ2" },
    { name: "SEO-008: SerpAPI connected", project: "SEO", status: "Done", priority: "Low", due: "", lastActivity: "2026-03-02", daysInStatus: 1, url: "https://trello.com/c/87OUbnpT" },
    { name: "SEO-014: SERP Analyzer service built", project: "SEO", status: "Done", priority: "Low", due: "", lastActivity: "2026-03-02", daysInStatus: 1, url: "https://trello.com/c/ff1p6LyM" },
    { name: "LOE SITE-007: Contact form backend (/api/contact via MailerLite)", project: "LOE", status: "Done", priority: "Low", due: "", lastActivity: "2026-03-02", daysInStatus: 1, url: "https://trello.com/c/Bu90FBNF" },
    { name: "LOE SITE-008: MailerLite automation triggers configured via API", project: "LOE", status: "Done", priority: "Low", due: "", lastActivity: "2026-03-02", daysInStatus: 1, url: "https://trello.com/c/gKqTsrfW" }
  ],
  financial: [
    { date: "2026-03-01", project: "PROD-001 SEO Toolkit", category: "COGS", description: "DataForSEO — keyword/SERP data", amount: -40, recurring: true },
    { date: "2026-03-01", project: "PROD-001 SEO Toolkit", category: "COGS", description: "SE Ranking — rank tracking (Essential)", amount: -52, recurring: true },
    { date: "2026-03-01", project: "Global", category: "OpEx", description: "Domain: bookrocket.ai (annual ~$12)", amount: -1, recurring: true },
    { date: "2026-03-01", project: "Global", category: "OpEx", description: "Domain: loveoverexile.com (annual ~$15)", amount: -1.25, recurring: true },
    { date: "2026-03-01", project: "Global", category: "OpEx", description: "Anthropic / Claude Code", amount: -200, recurring: true },
    { date: "2026-03-01", project: "Global", category: "OpEx", description: "GitHub (Free tier)", amount: 0, recurring: true },
    { date: "2026-03-01", project: "Global", category: "OpEx", description: "Bitwarden", amount: -0.83, recurring: true },
    { date: "2026-03-01", project: "CLIENT-001 Love Over Exile", category: "COGS", description: "Vercel hosting (Free tier)", amount: 0, recurring: true },
    { date: "2026-03-01", project: "CLIENT-001 Love Over Exile", category: "COGS", description: "Google Analytics 4 (Free)", amount: 0, recurring: false },
    { date: "2026-03-01", project: "CLIENT-001 Love Over Exile", category: "COGS", description: "MailerLite (Free tier)", amount: 0, recurring: true }
  ]
};
