// Auto-generated by Claude Code from Smith AI Agency Cockpit Google Sheet
// Spreadsheet: 1iZUsOKh1hAR0qtnu5HGk9WxTEXMuaZcvKY5pF0TVEJI
// Last sync: 2026-03-04T11:30:00Z

const DASHBOARD_DATA = {
  lastSync: "2026-03-04T11:30:00Z",

  // ============================================================
  // AGENCY-LEVEL KPIs
  // ============================================================
  agencyKPIs: [
    { name: "Monthly Burn", value: 295.08, target: 300, unit: "EUR", format: "currency", trend: "flat", description: "Total monthly operating costs" },
    { name: "Monthly Revenue (MRR)", value: 0, target: 500, unit: "EUR", format: "currency", trend: "flat", description: "Recurring revenue from all sources" },
    { name: "Active Projects", value: 6, target: null, unit: "", format: "number", trend: "flat", description: "Projects currently being worked on" },
    { name: "Projects on Track", value: 6, target: 6, unit: "", format: "ratio", trend: "flat", description: "Projects with Green RAG status" },
    { name: "Tasks This Week", value: 5, target: null, unit: "", format: "number", trend: "flat", description: "Tasks scheduled for this week" },
    { name: "Tasks Blocked", value: 2, target: 0, unit: "", format: "number", trend: "flat", description: "Tasks waiting on external action" },
    { name: "Tasks Completed (All Time)", value: 15, target: null, unit: "", format: "number", trend: "up", description: "Total tasks marked Done" },
    { name: "Runway", value: "N/A", target: null, unit: "months", format: "text", trend: "flat", description: "Months until revenue needed (bootstrapped)" },
  ],

  // ============================================================
  // PROJECT OVERVIEW
  // ============================================================
  overview: [
    { id: "client-001", project: "CLIENT-001 Love Over Exile", rag: "Green", omtmName: "Email signups/week", omtmValue: 0, omtmTarget: 50, trend: "flat", focus: "Content + GA4 setup" },
    { id: "client-002", project: "CLIENT-002 Hairgenetix", rag: "Green", omtmName: "Organic clicks/month", omtmValue: 1385, omtmTarget: 2000, trend: "flat", focus: "Content hub + SEO implementation" },
    { id: "prod-001", project: "PROD-001 SEO Toolkit", rag: "Green", omtmName: "Services at 80+/100", omtmValue: 3, omtmTarget: 5, trend: "up", focus: "AI Discovery v2 + Content service" },
    { id: "prod-002", project: "PROD-002 SellFunnel", rag: "Green", omtmName: "Research milestones", omtmValue: 1, omtmTarget: 4, trend: "flat", focus: "Architecture strategy" },
    { id: "infra-003", project: "INFRA-003 Monitoring", rag: "Green", omtmName: "Dashboard pages live", omtmValue: 1, omtmTarget: 5, trend: "up", focus: "Build cockpit dashboard" },
    { id: "infra-004", project: "INFRA-004 Task Management", rag: "Green", omtmName: "Board active", omtmValue: 1, omtmTarget: 1, trend: "flat", focus: "Maintain" },
  ],

  // ============================================================
  // PER-PROJECT DETAILED METRICS
  // ============================================================
  projectDetails: {
    "client-001": {
      name: "Love Over Exile", code: "CLIENT-001", type: "Client",
      description: "Author platform — memoir, blog, email community",
      url: "https://loveoverexile.com", repoUrl: "https://github.com/MrSmithNL/loveoverexile-website",
      metrics: [
        { name: "Email Signups/Week", value: 0, target: 50, format: "number", category: "Growth", trend: "flat", source: "MailerLite" },
        { name: "Organic Traffic/Month", value: 0, target: 1000, format: "number", category: "Traffic", trend: "flat", source: "GA4" },
        { name: "Waitlist Signups", value: 0, target: 500, format: "number", category: "Growth", trend: "flat", source: "MailerLite" },
        { name: "Content Published/Week", value: 0, target: 2, format: "number", category: "Content", trend: "flat", source: "Manual" },
        { name: "Avg Session Duration", value: 0, target: 120, format: "seconds", category: "Engagement", trend: "flat", source: "GA4" },
        { name: "SEO Score", value: 90, target: 95, format: "score", category: "SEO", trend: "flat", source: "SEO Toolkit" },
      ],
      missingMetrics: ["GA4 baselines not yet established", "MailerLite subscriber tracking not automated"],
    },
    "client-002": {
      name: "Hairgenetix", code: "CLIENT-002", type: "Client",
      description: "Shopify e-commerce — hair growth products, 9 languages, 1200+ reviews",
      url: "https://hairgenetix.com", repoUrl: null,
      metrics: [
        { name: "Organic Clicks/Month", value: 1385, target: 2000, format: "number", category: "Traffic", trend: "flat", source: "GSC" },
        { name: "Technical SEO", value: 87, target: 95, format: "score", category: "SEO", trend: "up", source: "SEO Toolkit" },
        { name: "AI Discovery Score", value: 79, target: 90, format: "score", category: "SEO", trend: "up", source: "SEO Toolkit" },
        { name: "Schema Markup", value: 10, target: 10, format: "score", category: "SEO", trend: "flat", source: "SEO Toolkit" },
        { name: "Avg Search Position", value: 7.8, target: 5.0, format: "position", category: "SEO", trend: "flat", source: "GSC", lowerIsBetter: true },
        { name: "Content Score", value: 64, target: 80, format: "score", category: "Content", trend: "flat", source: "SEO Toolkit" },
      ],
      missingMetrics: ["GA4 NOT installed — no session/conversion data", "Revenue tracking not connected"],
    },
    "prod-001": {
      name: "SEO Toolkit", code: "PROD-001", type: "Product",
      description: "Modular SEO analysis platform — 5 services",
      url: null, repoUrl: "https://github.com/MrSmithNL/seo-toolkit",
      metrics: [
        { name: "Technical Audit Score", value: 90, target: 95, format: "score", category: "Quality", trend: "flat", source: "Internal" },
        { name: "Content Optimizer Score", value: 74, target: 80, format: "score", category: "Quality", trend: "flat", source: "Internal" },
        { name: "AI Discovery Score", value: 100, target: 100, format: "score", category: "Quality", trend: "flat", source: "Internal" },
        { name: "Keywords Service", value: 1, target: 1, format: "boolean", category: "Delivery", trend: "flat", source: "Internal", label: "Live" },
        { name: "SERP Analyzer", value: 1, target: 1, format: "boolean", category: "Delivery", trend: "flat", source: "Internal", label: "Live" },
        { name: "Services at 80+/100", value: 3, target: 5, format: "number", category: "Quality", trend: "up", source: "Internal" },
      ],
      missingMetrics: ["No usage/adoption metrics (no users yet)", "No revenue metrics"],
    },
    "prod-002": {
      name: "SellFunnel", code: "PROD-002", type: "Product",
      description: "Sales funnel automation platform — research phase",
      url: null, repoUrl: null,
      metrics: [
        { name: "Research Milestones", value: 1, target: 4, format: "number", category: "Progress", trend: "flat", source: "Manual" },
      ],
      missingMetrics: ["NO success KPIs defined", "No architecture milestones tracked", "No competitive analysis metrics", "No market sizing metrics"],
    },
    "infra-003": {
      name: "Monitoring & BI Dashboard", code: "INFRA-003", type: "Infrastructure",
      description: "Agency performance cockpit — Google Sheets + custom dashboard",
      url: "https://mrsmithnl.github.io/agency-dashboard/", repoUrl: "https://github.com/MrSmithNL/agency-dashboard",
      metrics: [
        { name: "Dashboard Pages Live", value: 1, target: 5, format: "number", category: "Delivery", trend: "up", source: "Internal" },
        { name: "Data Sources Connected", value: 2, target: 6, format: "number", category: "Delivery", trend: "flat", source: "Internal" },
        { name: "Auto-Sync Active", value: 0, target: 1, format: "boolean", category: "Automation", trend: "flat", source: "Internal", label: "Not yet" },
      ],
      missingMetrics: ["Data freshness SLA not defined"],
    },
    "infra-004": {
      name: "Task Management", code: "INFRA-004", type: "Infrastructure",
      description: "Trello-based task management for all agency projects",
      url: "https://trello.com/b/XK7SWbJh/ai-agency-all-projects", repoUrl: null,
      metrics: [
        { name: "Board Active", value: 1, target: 1, format: "boolean", category: "Status", trend: "flat", source: "Trello", label: "Active" },
        { name: "Total Cards", value: 33, target: null, format: "number", category: "Volume", trend: "flat", source: "Trello" },
        { name: "Cards Completed", value: 15, target: null, format: "number", category: "Throughput", trend: "up", source: "Trello" },
        { name: "Cards Blocked", value: 2, target: 0, format: "number", category: "Health", trend: "flat", source: "Trello" },
      ],
      missingMetrics: [],
    },
  },

  // ============================================================
  // SCHEDULES (Calendar Tab)
  // ============================================================
  schedules: [
    { id: "sch-001", name: "Daily Trello Sync", cron: "0 6 * * *", humanCron: "Daily at 06:00 UTC", project: "INFRA-003", status: "planned", type: "recipe", description: "Sync Trello board data to Google Sheet and dashboard data.js" },
    { id: "sch-002", name: "Weekly History Snapshot", cron: "0 7 * * 1", humanCron: "Mondays at 07:00 UTC", project: "INFRA-003", status: "planned", type: "recipe", description: "Capture weekly snapshot of all project metrics for trend tracking in History tab" },
    { id: "sch-003", name: "Monthly Competitor Monitoring", cron: "0 8 1 * *", humanCron: "1st of month at 08:00 UTC", project: "All", status: "active", type: "standing-order", description: "Check all competitors for pricing changes, new features, AI capabilities, acquisitions. Log new findings only. Auto-create tasks for new recommendations." },
    { id: "sch-004", name: "Monthly Financial Dashboard Update", cron: "0 8 1 * *", humanCron: "1st of month at 08:00 UTC", project: "All", status: "active", type: "standing-order", description: "Update financial-dashboard.md, check all accounts-and-access.md files, update cost figures, log AI usage, update P&L." },
    { id: "sch-005", name: "Monthly Template Drift Check", cron: "0 8 1 * *", humanCron: "1st of month at 08:00 UTC", project: "All", status: "active", type: "standing-order", description: "Compare all blueprint templates against active project files, flag structural differences, propagate improvements." },
    { id: "sch-006", name: "Weekly AI Summary Report", cron: "0 7 * * 1", humanCron: "Mondays at 07:00 UTC", project: "All", status: "planned", type: "recipe", description: "Claude reads all Sheet tabs, compares to previous week, generates plain-English weekly summary report." },
    { id: "sch-007", name: "Architecture Maintenance", cron: "* * * * *", humanCron: "After every change (continuous)", project: "All", status: "active", type: "standing-order", description: "Update architecture.md, todo.md, diagrams, Trello, commit/push after any infrastructure change. Runs as background agents." },
    { id: "sch-008", name: "Dashboard Data Refresh", cron: "* * * * *", humanCron: "Every Claude session", project: "INFRA-003", status: "active", type: "standing-order", description: "Regenerate data.js from Google Sheet during each Claude Code session." },
  ],

  // ============================================================
  // RECOMMENDATIONS (Continuous Improvement Tab)
  // ============================================================
  recommendations: [
    // --- PROD-001 SEO Toolkit: 20 recommendations ---
    { id: "SEO-S-001", project: "PROD-001 SEO Toolkit", source: "competitor", category: "Strategy", title: "Start as internal tool, prove on Love Over Exile", description: "All competitors charge $50-999/mo. Build and validate the toolkit internally on Love Over Exile before selling externally. Reduces risk, proves value.", scoreType: "competitor", scores: { strategic: 3, revenue: 2, effort: 3, urgency: 1 }, total: 9, maxTotal: 12, status: "proposed", priority: "High", sourceRef: "S-001" },
    { id: "SEO-S-002", project: "PROD-001 SEO Toolkit", source: "competitor", category: "Strategy", title: "Price at $99-199/mo entry tier", description: "Below Ahrefs ($99) and SEMrush ($119), above SE Ranking ($31). Sweet spot for solo operators and small agencies.", scoreType: "competitor", scores: { strategic: 2, revenue: 3, effort: 3, urgency: 1 }, total: 9, maxTotal: 12, status: "proposed", priority: "High", sourceRef: "S-002" },
    { id: "SEO-S-003", project: "PROD-001 SEO Toolkit", source: "competitor", category: "Strategy", title: "Position as \"autonomous AI SEO\"", description: "No competitor has autonomous agents. Position as 'autonomous AI SEO' — agents that work on their own, not just dashboards. Unique market gap.", scoreType: "competitor", scores: { strategic: 3, revenue: 3, effort: 3, urgency: 2 }, total: 11, maxTotal: 12, status: "proposed", priority: "Critical", sourceRef: "S-003" },
    { id: "SEO-S-004", project: "PROD-001 SEO Toolkit", source: "competitor", category: "Strategy", title: "Per-website pricing model", description: "Offer per-website pricing instead of per-user like Ahrefs/SEMrush. Better fit for agencies managing multiple client sites.", scoreType: "competitor", scores: { strategic: 2, revenue: 2, effort: 3, urgency: 1 }, total: 8, maxTotal: 12, status: "proposed", priority: "High", sourceRef: "S-004" },
    { id: "SEO-S-005", project: "PROD-001 SEO Toolkit", source: "competitor", category: "Strategy", title: "Target solo operators + small agencies", description: "Ahrefs/SEMrush are overkill for solopreneurs. Focus on underserved solo operators and small agencies first.", scoreType: "competitor", scores: { strategic: 2, revenue: 2, effort: 3, urgency: 1 }, total: 8, maxTotal: 12, status: "proposed", priority: "High", sourceRef: "S-005" },
    { id: "SEO-M-001", project: "PROD-001 SEO Toolkit", source: "competitor", category: "Marketing", title: "\"Set it and forget it\" messaging", description: "Lead with autonomous agent messaging — agents work on their own, not just dashboards. Unique vs all competitors.", scoreType: "competitor", scores: { strategic: 3, revenue: 2, effort: 3, urgency: 2 }, total: 10, maxTotal: 12, status: "proposed", priority: "Critical", sourceRef: "M-001" },
    { id: "SEO-M-002", project: "PROD-001 SEO Toolkit", source: "competitor", category: "Marketing", title: "Create comparison pages vs Ahrefs/SEMrush", description: "Standard SaaS SEO strategy. 'SEO Toolkit vs Ahrefs', 'vs SEMrush' comparison pages drive purchase-intent traffic.", scoreType: "competitor", scores: { strategic: 2, revenue: 2, effort: 2, urgency: 1 }, total: 7, maxTotal: 12, status: "proposed", priority: "High", sourceRef: "M-002" },
    { id: "SEO-M-003", project: "PROD-001 SEO Toolkit", source: "competitor", category: "Marketing", title: "Publish LOE monthly reports as case studies", description: "Publish monthly SEO reports from Love Over Exile as case studies. Proves our own tool works on real data.", scoreType: "competitor", scores: { strategic: 2, revenue: 3, effort: 2, urgency: 1 }, total: 8, maxTotal: 12, status: "proposed", priority: "High", sourceRef: "M-003" },
    { id: "SEO-M-004", project: "PROD-001 SEO Toolkit", source: "competitor", category: "Marketing", title: "Free audit report as lead magnet", description: "Like Screaming Frog's free crawl. Free SEO audit drives upgrades to paid plans.", scoreType: "competitor", scores: { strategic: 1, revenue: 3, effort: 2, urgency: 1 }, total: 7, maxTotal: 12, status: "proposed", priority: "High", sourceRef: "M-004" },
    { id: "SEO-M-005", project: "PROD-001 SEO Toolkit", source: "competitor", category: "Marketing", title: "Target content creators via Book Rocket", description: "Content creators and authors are underserved by all major SEO tools. Reach them through Book Rocket vertical.", scoreType: "competitor", scores: { strategic: 2, revenue: 2, effort: 2, urgency: 0 }, total: 6, maxTotal: 12, status: "proposed", priority: "Medium", sourceRef: "M-005" },
    { id: "SEO-T-001", project: "PROD-001 SEO Toolkit", source: "competitor", category: "Technology", title: "AI Discovery Agent", description: "No competitor tracks AI search engine visibility. Build agent that audits ChatGPT, Perplexity, Gemini findability.", scoreType: "competitor", scores: { strategic: 3, revenue: 3, effort: 0, urgency: 3 }, total: 9, maxTotal: 12, status: "proposed", priority: "High", sourceRef: "T-001" },
    { id: "SEO-T-002", project: "PROD-001 SEO Toolkit", source: "competitor", category: "Technology", title: "Automated content optimization", description: "Like Surfer SEO but AI-driven. Automated content optimization suggestions based on top-ranking pages.", scoreType: "competitor", scores: { strategic: 3, revenue: 3, effort: 0, urgency: 2 }, total: 8, maxTotal: 12, status: "proposed", priority: "High", sourceRef: "T-002" },
    { id: "SEO-T-003", project: "PROD-001 SEO Toolkit", source: "competitor", category: "Technology", title: "Earned link discovery", description: "Find unlinked mentions and broken links automatically. Ahrefs has this but manual, not automated.", scoreType: "competitor", scores: { strategic: 2, revenue: 2, effort: 1, urgency: 2 }, total: 7, maxTotal: 12, status: "proposed", priority: "High", sourceRef: "T-003" },
    { id: "SEO-T-004", project: "PROD-001 SEO Toolkit", source: "competitor", category: "Technology", title: "Multi-site dashboard", description: "Manage all client sites from one view. SEMrush/Ahrefs have this, essential for agencies.", scoreType: "competitor", scores: { strategic: 1, revenue: 2, effort: 1, urgency: 1 }, total: 5, maxTotal: 12, status: "proposed", priority: "Medium", sourceRef: "T-004" },
    { id: "SEO-T-005", project: "PROD-001 SEO Toolkit", source: "competitor", category: "Technology", title: "White-label reports for agencies", description: "SEMrush offers this at $230+/mo tier. Branded reports increase agency stickiness.", scoreType: "competitor", scores: { strategic: 1, revenue: 2, effort: 1, urgency: 0 }, total: 4, maxTotal: 12, status: "proposed", priority: "Medium", sourceRef: "T-005" },
    { id: "SEO-T-006", project: "PROD-001 SEO Toolkit", source: "competitor", category: "Technology", title: "Google Search Console integration", description: "Automated GSC integration, not just data display. All competitors have this — table stakes.", scoreType: "competitor", scores: { strategic: 2, revenue: 2, effort: 2, urgency: 3 }, total: 9, maxTotal: 12, status: "proposed", priority: "High", sourceRef: "T-006" },
    { id: "SEO-T-007", project: "PROD-001 SEO Toolkit", source: "competitor", category: "Technology", title: "Schema markup generator", description: "Screaming Frog detects schema issues but doesn't fix them. Generate correct schema from content analysis.", scoreType: "competitor", scores: { strategic: 1, revenue: 1, effort: 1, urgency: 1 }, total: 4, maxTotal: 12, status: "proposed", priority: "Medium", sourceRef: "T-007" },
    { id: "SEO-SV-001", project: "PROD-001 SEO Toolkit", source: "competitor", category: "Services", title: "Self-serve setup, no onboarding calls", description: "Unlike Salesforce/HubSpot that require onboarding. Self-serve setup reduces CAC and friction.", scoreType: "competitor", scores: { strategic: 2, revenue: 2, effort: 2, urgency: 1 }, total: 7, maxTotal: 12, status: "proposed", priority: "High", sourceRef: "SV-001" },
    { id: "SEO-SV-002", project: "PROD-001 SEO Toolkit", source: "competitor", category: "Services", title: "In-product tutorials for non-technical users", description: "Moz does this well with their learning centre. Contextual help reduces support burden.", scoreType: "competitor", scores: { strategic: 1, revenue: 1, effort: 1, urgency: 1 }, total: 4, maxTotal: 12, status: "proposed", priority: "Medium", sourceRef: "SV-002" },
    { id: "SEO-SV-003", project: "PROD-001 SEO Toolkit", source: "competitor", category: "Services", title: "Community forum for users", description: "Like Ahrefs community. User forums drive retention and reduce churn.", scoreType: "competitor", scores: { strategic: 1, revenue: 1, effort: 1, urgency: 0 }, total: 3, maxTotal: 12, status: "proposed", priority: "Low", sourceRef: "SV-003" },

    // --- Book Rocket: 19 recommendations ---
    { id: "BR-S-001", project: "Book Rocket", source: "competitor", category: "Strategy", title: "Position as \"AI-powered book promotion\"", description: "No competitor combines SEO + Marketing for authors. First-mover advantage in AI-powered book promotion.", scoreType: "competitor", scores: { strategic: 3, revenue: 3, effort: 3, urgency: 2 }, total: 11, maxTotal: 12, status: "proposed", priority: "Critical", sourceRef: "S-001" },
    { id: "BR-S-002", project: "Book Rocket", source: "competitor", category: "Strategy", title: "Price at $49-99/mo", description: "Below Reedsy premium, accessible to self-published authors. Sweet spot for indie author budgets.", scoreType: "competitor", scores: { strategic: 2, revenue: 3, effort: 3, urgency: 1 }, total: 9, maxTotal: 12, status: "proposed", priority: "High", sourceRef: "S-002" },
    { id: "BR-S-003", project: "Book Rocket", source: "competitor", category: "Strategy", title: "Prove on Love Over Exile first", description: "Agency principle: prove on own projects before selling. Love Over Exile is the perfect test case.", scoreType: "competitor", scores: { strategic: 3, revenue: 2, effort: 3, urgency: 1 }, total: 9, maxTotal: 12, status: "proposed", priority: "High", sourceRef: "S-003" },
    { id: "BR-S-004", project: "Book Rocket", source: "competitor", category: "Strategy", title: "Partner with self-publishing platforms", description: "Partner with KDP, IngramSpark for distribution. No competitor does this with AI.", scoreType: "competitor", scores: { strategic: 2, revenue: 2, effort: 1, urgency: 1 }, total: 6, maxTotal: 12, status: "proposed", priority: "Medium", sourceRef: "S-004" },
    { id: "BR-S-005", project: "Book Rocket", source: "competitor", category: "Strategy", title: "Book launch package as one-time fee", description: "Authors have specific launch windows. Offer 'book launch' package as one-time fee alongside subscription.", scoreType: "competitor", scores: { strategic: 2, revenue: 3, effort: 2, urgency: 1 }, total: 8, maxTotal: 12, status: "proposed", priority: "High", sourceRef: "S-005" },
    { id: "BR-M-001", project: "Book Rocket", source: "competitor", category: "Marketing", title: "Target authors on Reddit", description: "r/selfpublish, r/writing are the largest author communities. Low-cost, high-engagement marketing.", scoreType: "competitor", scores: { strategic: 2, revenue: 2, effort: 3, urgency: 1 }, total: 8, maxTotal: 12, status: "proposed", priority: "High", sourceRef: "M-001" },
    { id: "BR-M-002", project: "Book Rocket", source: "competitor", category: "Marketing", title: "Author SEO Guide lead magnet", description: "No good author-specific SEO guide exists. Free guide drives email signups and demonstrates expertise.", scoreType: "competitor", scores: { strategic: 2, revenue: 3, effort: 2, urgency: 1 }, total: 8, maxTotal: 12, status: "proposed", priority: "High", sourceRef: "M-002" },
    { id: "BR-M-003", project: "Book Rocket", source: "competitor", category: "Marketing", title: "Love Over Exile case study", description: "'From zero to X traffic in Y months' — proves the system works for a real author.", scoreType: "competitor", scores: { strategic: 3, revenue: 3, effort: 2, urgency: 1 }, total: 9, maxTotal: 12, status: "proposed", priority: "High", sourceRef: "M-003" },
    { id: "BR-M-004", project: "Book Rocket", source: "competitor", category: "Marketing", title: "Partner with book marketing podcasts", description: "Reach BookBub, Written Word Media audiences. Builds credibility in the author space.", scoreType: "competitor", scores: { strategic: 1, revenue: 2, effort: 1, urgency: 0 }, total: 4, maxTotal: 12, status: "proposed", priority: "Medium", sourceRef: "M-004" },
    { id: "BR-M-005", project: "Book Rocket", source: "competitor", category: "Marketing", title: "Free author website audit", description: "Similar to Screaming Frog's free tier strategy. Free audit drives paid conversions.", scoreType: "competitor", scores: { strategic: 1, revenue: 2, effort: 2, urgency: 1 }, total: 6, maxTotal: 12, status: "proposed", priority: "Medium", sourceRef: "M-005" },
    { id: "BR-T-001", project: "Book Rocket", source: "competitor", category: "Technology", title: "Author-specific keyword research", description: "Book titles, genres, reading topics. No SEO tool targets author-specific keywords.", scoreType: "competitor", scores: { strategic: 3, revenue: 2, effort: 1, urgency: 2 }, total: 8, maxTotal: 12, status: "proposed", priority: "High", sourceRef: "T-001" },
    { id: "BR-T-002", project: "Book Rocket", source: "competitor", category: "Technology", title: "Book content to web content pipeline", description: "Turn chapters into articles, excerpts into blog posts. Unique to Book Rocket — no competitor does this.", scoreType: "competitor", scores: { strategic: 3, revenue: 3, effort: 0, urgency: 2 }, total: 8, maxTotal: 12, status: "proposed", priority: "High", sourceRef: "T-002" },
    { id: "BR-T-003", project: "Book Rocket", source: "competitor", category: "Technology", title: "AI Discovery for book queries", description: "Optimize for 'best books about X' queries in ChatGPT/Gemini. Builds on SEO Toolkit AI Discovery agent.", scoreType: "competitor", scores: { strategic: 3, revenue: 2, effort: 1, urgency: 3 }, total: 9, maxTotal: 12, status: "proposed", priority: "High", sourceRef: "T-003" },
    { id: "BR-T-004", project: "Book Rocket", source: "competitor", category: "Technology", title: "Review site monitoring", description: "Monitor Goodreads, Amazon, BookBub ratings. Authors need this, no automated tool exists.", scoreType: "competitor", scores: { strategic: 1, revenue: 1, effort: 1, urgency: 1 }, total: 4, maxTotal: 12, status: "proposed", priority: "Medium", sourceRef: "T-004" },
    { id: "BR-T-005", project: "Book Rocket", source: "competitor", category: "Technology", title: "Social media content from book content", description: "Marketing Engine feature packaged for authors. Generate social posts from book excerpts.", scoreType: "competitor", scores: { strategic: 1, revenue: 2, effort: 2, urgency: 1 }, total: 6, maxTotal: 12, status: "proposed", priority: "Medium", sourceRef: "T-005" },
    { id: "BR-SV-001", project: "Book Rocket", source: "competitor", category: "Services", title: "Book Launch Playbook included", description: "Step-by-step guide included with subscription. Authors need hand-holding, not just tools.", scoreType: "competitor", scores: { strategic: 2, revenue: 2, effort: 2, urgency: 1 }, total: 7, maxTotal: 12, status: "proposed", priority: "High", sourceRef: "SV-001" },
    { id: "BR-SV-002", project: "Book Rocket", source: "competitor", category: "Services", title: "Author onboarding wizard", description: "'Tell us about your book' wizard that auto-configures everything. Authors are non-technical.", scoreType: "competitor", scores: { strategic: 2, revenue: 2, effort: 1, urgency: 1 }, total: 6, maxTotal: 12, status: "proposed", priority: "Medium", sourceRef: "SV-002" },
    { id: "BR-SV-003", project: "Book Rocket", source: "competitor", category: "Services", title: "Monthly plain-English book report", description: "'How your book is doing online' report. Authors don't understand SEO metrics.", scoreType: "competitor", scores: { strategic: 1, revenue: 2, effort: 2, urgency: 0 }, total: 5, maxTotal: 12, status: "proposed", priority: "Medium", sourceRef: "SV-003" },
    { id: "BR-SV-004", project: "Book Rocket", source: "competitor", category: "Services", title: "Author community forum", description: "Builds retention and word-of-mouth. Authors love sharing promotion strategies.", scoreType: "competitor", scores: { strategic: 1, revenue: 1, effort: 1, urgency: 0 }, total: 3, maxTotal: 12, status: "proposed", priority: "Low", sourceRef: "SV-004" },
  ],

  // ============================================================
  // AGENTS (Agents Tab)
  // ============================================================
  agents: {
    departments: [
      {
        id: "prod-001", name: "SEO Toolkit", type: "Product", status: "active",
        agentCount: 10, liveCount: 5, overallCompleteness: 50,
        agents: [
          { id: "seo-technical-audit", name: "Technical Audit", tier: 1, status: "live", recipeId: "rcp_fUfiRNt8Bh8b", qualityScore: 90, capabilityScore: 65, description: "Automated technical SEO audit — crawls site, checks structure, performance, accessibility", tools: ["GSC", "WebFetch", "DataForSEO"], benchmarks: [{ competitor: "Screaming Frog", capability: "Deep crawl analysis (1000s pages/min)", ourCoverage: 70 }, { competitor: "Ahrefs Site Audit", capability: "100+ technical checks with fix suggestions", ourCoverage: 60 }, { competitor: "SEMrush Site Audit", capability: "140+ checks + auto-fix suggestions", ourCoverage: 55 }], subAgents: [] },
          { id: "seo-content-optimizer", name: "Content Optimizer", tier: 1, status: "live", recipeId: "rcp_-msCRAZI2mln", qualityScore: 74, capabilityScore: 50, description: "Analyzes content quality and provides optimization recommendations", tools: ["WebFetch", "invoke_llm"], benchmarks: [{ competitor: "Surfer SEO", capability: "NLP scoring against top-ranking pages in real-time", ourCoverage: 40 }, { competitor: "Clearscope", capability: "Content grading with A-F scores + semantic terms", ourCoverage: 50 }], subAgents: [] },
          { id: "seo-keyword-research", name: "Keyword Research", tier: 1, status: "live", recipeId: "rcp_083WOBwKYeNo", qualityScore: null, capabilityScore: 45, description: "AI-powered keyword clustering and opportunity identification", tools: ["GSC", "SerpAPI", "Composio Search", "invoke_llm"], benchmarks: [{ competitor: "Ahrefs Keywords Explorer", capability: "Keyword difficulty + volume for 170 countries", ourCoverage: 30 }, { competitor: "SEMrush Keyword Magic Tool", capability: "20B+ keyword database with intent data", ourCoverage: 25 }], subAgents: [] },
          { id: "seo-serp-analyzer", name: "SERP Analyzer", tier: 1, status: "live", recipeId: "rcp_tebS66AkhuYq", qualityScore: null, capabilityScore: 55, description: "Analyzes search engine results pages for competitive insights", tools: ["SerpAPI", "invoke_llm"], benchmarks: [{ competitor: "Ahrefs SERP Overview", capability: "Full SERP feature tracking + historical data", ourCoverage: 45 }, { competitor: "Surfer SEO SERP Analyzer", capability: "Top-ranking page analysis with NLP scoring", ourCoverage: 50 }], subAgents: [] },
          { id: "seo-ai-discovery", name: "AI Discovery Audit", tier: 1, status: "live", recipeId: "rcp_3LBwPfkiTtRT", qualityScore: 100, capabilityScore: 95, description: "34-factor audit for AI search engine visibility (ChatGPT, Perplexity, Gemini, AI Overviews)", tools: ["WebFetch", "invoke_llm", "Composio Search"], benchmarks: [{ competitor: "No direct competitor", capability: "AI search optimization is unaddressed by all major SEO tools", ourCoverage: 95 }], subAgents: [] },
          { id: "seo-rank-tracker", name: "Rank Tracker", tier: 2, status: "planned", recipeId: null, qualityScore: null, capabilityScore: 0, description: "Automated keyword position tracking over time", tools: [], benchmarks: [{ competitor: "SE Ranking", capability: "Daily rank tracking for 1000+ keywords", ourCoverage: 0 }, { competitor: "Ahrefs Rank Tracker", capability: "Desktop + mobile tracking with SERP features", ourCoverage: 0 }], subAgents: [] },
          { id: "seo-content-writer", name: "Content Writer", tier: 2, status: "planned", recipeId: null, qualityScore: null, capabilityScore: 0, description: "AI content generation from keyword research data", tools: [], benchmarks: [{ competitor: "Surfer SEO AI Writer", capability: "SEO-optimized article generation with NLP", ourCoverage: 0 }, { competitor: "SEMrush ContentShake AI", capability: "AI content creation with NLP optimization", ourCoverage: 0 }], subAgents: [] },
          { id: "seo-link-builder", name: "Link Builder", tier: 2, status: "planned", recipeId: null, qualityScore: null, capabilityScore: 0, description: "Automated link building with 6 specialized sub-agents", tools: [], benchmarks: [{ competitor: "Ahrefs", capability: "16 trillion link index + content explorer", ourCoverage: 0 }, { competitor: "SEMrush Link Building Tool", capability: "Prospect discovery + outreach management", ourCoverage: 0 }], subAgents: [{ id: "lb-backlink-profiler", name: "Backlink Profiler", status: "planned" }, { id: "lb-prospect-discovery", name: "Prospect Discovery", status: "planned" }, { id: "lb-linkable-asset", name: "Linkable Asset Creator", status: "planned" }, { id: "lb-outreach-manager", name: "Outreach Manager", status: "planned" }, { id: "lb-competitor-spy", name: "Competitor Link Spy", status: "planned" }, { id: "lb-health-monitor", name: "Link Health Monitor", status: "planned" }] },
          { id: "seo-competitor-monitor", name: "Competitor Monitor", tier: 3, status: "planned", recipeId: null, qualityScore: null, capabilityScore: 0, description: "Automated competitive intelligence and positioning tracking", tools: [], benchmarks: [{ competitor: "SEMrush Competitive Research", capability: "Traffic analytics + gap analysis + position changes", ourCoverage: 0 }], subAgents: [] },
          { id: "seo-reporter", name: "Reporter", tier: 3, status: "planned", recipeId: null, qualityScore: null, capabilityScore: 0, description: "Automated plain-English SEO reporting with charts and recommendations", tools: [], benchmarks: [{ competitor: "SEMrush My Reports", capability: "White-label PDF reports with custom branding", ourCoverage: 0 }], subAgents: [] },
        ]
      },
      {
        id: "prod-002", name: "SellFunnel", type: "Product", status: "research",
        agentCount: 0, liveCount: 0, overallCompleteness: 0, agents: []
      },
      {
        id: "prod-003", name: "Marketing Engine", type: "Product", status: "not-started",
        agentCount: 0, liveCount: 0, overallCompleteness: 0, agents: []
      },
      {
        id: "infra", name: "Infrastructure Services", type: "Infrastructure", status: "active",
        agentCount: 5, liveCount: 2, overallCompleteness: 40,
        agents: [
          { id: "infra-001", name: "Overnight CLI Runner", tier: 1, status: "planned", recipeId: null, qualityScore: null, capabilityScore: 0, description: "Autonomous overnight task runner via Claude Code headless mode + cron", tools: [], benchmarks: [], subAgents: [] },
          { id: "infra-002", name: "Project Template Repo", tier: 1, status: "planned", recipeId: null, qualityScore: null, capabilityScore: 0, description: "GitHub template for instant project setup with 7-file blueprint", tools: [], benchmarks: [], subAgents: [] },
          { id: "infra-003", name: "Monitoring Dashboard", tier: 1, status: "live", recipeId: null, qualityScore: null, capabilityScore: 35, description: "Agency performance cockpit with drill-down project pages", tools: ["GitHub Pages", "Chart.js", "Google Sheets"], benchmarks: [], subAgents: [] },
          { id: "infra-004", name: "Task Management", tier: 1, status: "live", recipeId: null, qualityScore: null, capabilityScore: 70, description: "Trello-based task management via Composio MCP (15 tools)", tools: ["Trello", "Composio"], benchmarks: [], subAgents: [] },
          { id: "infra-005", name: "Continuous Improvement", tier: 1, status: "active", recipeId: null, qualityScore: null, capabilityScore: 25, description: "Research and improvement engine — 10 coverage areas, 4-criterion filter", tools: [], benchmarks: [], subAgents: [] },
        ]
      }
    ]
  },

  // ============================================================
  // TASKS
  // ============================================================
  tasks: [
    { name: "Financial: Complete cost inventory checklist", project: "INFRA", status: "This Week", priority: "Medium", due: "", lastActivity: "2026-03-02", daysInStatus: 1, url: "https://trello.com/c/UZWj0sVZ" },
    { name: "INFRA-005: First research cycle — Claude Code best practices", project: "INFRA", status: "This Week", priority: "Medium", due: "", lastActivity: "2026-03-02", daysInStatus: 1, url: "https://trello.com/c/H0wdllLy" },
    { name: "LOE SITE-003: Generate site images (Imagen 4)", project: "LOE", status: "This Week", priority: "Medium", due: "", lastActivity: "2026-03-02", daysInStatus: 1, url: "https://trello.com/c/aHpfBBQT" },
    { name: "LOE: Fix SEO audit warnings (36 items)", project: "LOE", status: "This Week", priority: "Medium", due: "", lastActivity: "2026-03-02", daysInStatus: 1, url: "https://trello.com/c/g1sVP85U" },
    { name: "HG: Fix H1 tags + meta titles/descriptions (34 pages)", project: "Hairgenetix", status: "This Week", priority: "Medium", due: "", lastActivity: "2026-03-03", daysInStatus: 0, url: "https://trello.com/c/zVihksrx" },
    { name: "SEO-001: Create DataForSEO account + deposit $50", project: "SEO", status: "Blocked", priority: "Low", due: "", lastActivity: "2026-03-02", daysInStatus: 1, url: "https://trello.com/c/Pal98Bld" },
    { name: "SEO-003: Start SE Ranking 14-day free trial", project: "SEO", status: "Blocked", priority: "Low", due: "", lastActivity: "2026-03-02", daysInStatus: 1, url: "https://trello.com/c/xWosGhaB" },
    { name: "INFRA-001: Set up Overnight CLI Runner", project: "INFRA", status: "Backlog", priority: "Low", due: "", lastActivity: "2026-03-02", daysInStatus: 1, url: "https://trello.com/c/Hg0V0p37" },
    { name: "INFRA-002: Create Project Template Repo", project: "INFRA", status: "Backlog", priority: "Low", due: "", lastActivity: "2026-03-02", daysInStatus: 1, url: "https://trello.com/c/qpaWjSRZ" },
    { name: "INFRA-003: Set up BI Dashboard (Looker Studio + Sheets)", project: "INFRA", status: "Backlog", priority: "Low", due: "", lastActivity: "2026-03-02", daysInStatus: 1, url: "https://trello.com/c/V3G7QEBB" },
    { name: "INFRA-005: Set up knowledge base folder structure", project: "INFRA", status: "Backlog", priority: "Low", due: "", lastActivity: "2026-03-02", daysInStatus: 1, url: "https://trello.com/c/bIsd6Daz" },
    { name: "SF-001: SellFunnel architecture strategy", project: "SF", status: "Backlog", priority: "Low", due: "", lastActivity: "2026-03-02", daysInStatus: 1, url: "https://trello.com/c/E1bVnPJS" },
    { name: "TOOL-001: Fix Bitwarden CLI unlock", project: "INFRA", status: "Backlog", priority: "Low", due: "", lastActivity: "2026-03-02", daysInStatus: 1, url: "https://trello.com/c/W6pr3Md9" },
    { name: "TOOL-002: Set up Bitwarden vault structure", project: "INFRA", status: "Backlog", priority: "Low", due: "", lastActivity: "2026-03-02", daysInStatus: 1, url: "https://trello.com/c/vbbItYfl" },
    { name: "SEO-024: Schedule recurring SEO audits", project: "SEO", status: "Backlog", priority: "Low", due: "", lastActivity: "2026-03-02", daysInStatus: 1, url: "https://trello.com/c/NoIwEBzv" },
    { name: "SEO-025: Apply audit recommendations to LOE", project: "SEO", status: "Backlog", priority: "Low", due: "", lastActivity: "2026-03-02", daysInStatus: 1, url: "https://trello.com/c/983gPPot" },
    { name: "SEO-007: Connect SEMrush via Rube", project: "SEO", status: "Backlog", priority: "Low", due: "", lastActivity: "2026-03-02", daysInStatus: 1, url: "https://trello.com/c/afwNYpG5" },
    { name: "LOE: Malcolm — activate 3 MailerLite automations in UI", project: "LOE", status: "Backlog", priority: "Low", due: "", lastActivity: "2026-03-02", daysInStatus: 1, url: "https://trello.com/c/Pq5XyedR" },
    { name: "INFRA-004: Set up Trello board + migrate tasks", project: "INFRA", status: "Done", priority: "Low", due: "", lastActivity: "2026-03-02", daysInStatus: 1, url: "https://trello.com/c/ykRH92qT" },
    { name: "LOE SITE-004: Connect MailerLite forms", project: "LOE", status: "Done", priority: "Low", due: "", lastActivity: "2026-03-02", daysInStatus: 1, url: "https://trello.com/c/PczVO3lP" },
    { name: "LOE SITE-002: Set up Google Analytics 4", project: "LOE", status: "Done", priority: "Low", due: "", lastActivity: "2026-03-02", daysInStatus: 1, url: "https://trello.com/c/aPvTaCH5" },
    { name: "LOE SITE-006: DNS cutover to Vercel (GoDaddy)", project: "LOE", status: "Done", priority: "Low", due: "", lastActivity: "2026-03-02", daysInStatus: 1, url: "https://trello.com/c/y7YmNl2C" },
    { name: "SEO-012: Content Optimizer service built", project: "SEO", status: "Done", priority: "Low", due: "", lastActivity: "2026-03-02", daysInStatus: 1, url: "https://trello.com/c/GnqmH3GY" },
    { name: "CLIENT-002: Hairgenetix — initial setup + first SEO audit", project: "Hairgenetix", status: "Done", priority: "Low", due: "", lastActivity: "2026-03-03", daysInStatus: 0, url: "https://trello.com/c/ozxhDug4" },
    { name: "SEO-013: AI Discovery Audit service built", project: "SEO", status: "Done", priority: "Low", due: "", lastActivity: "2026-03-02", daysInStatus: 1, url: "https://trello.com/c/t1IARwQX" },
    { name: "SEO-010: Build Audit Agent", project: "SEO", status: "Done", priority: "Low", due: "", lastActivity: "2026-03-02", daysInStatus: 1, url: "https://trello.com/c/c7SvuUcm" },
    { name: "SEO-011: Build Keywords Agent", project: "SEO", status: "Done", priority: "Low", due: "", lastActivity: "2026-03-02", daysInStatus: 1, url: "https://trello.com/c/HcZEcGTl" },
    { name: "SEO-002: Google Search Console connected", project: "SEO", status: "Done", priority: "Low", due: "", lastActivity: "2026-03-02", daysInStatus: 1, url: "https://trello.com/c/tKCrmNUh" },
    { name: "LOE WP-005: Write and publish real content", project: "LOE", status: "Done", priority: "Low", due: "", lastActivity: "2026-03-02", daysInStatus: 1, url: "https://trello.com/c/PTNGbAQ2" },
    { name: "SEO-008: SerpAPI connected", project: "SEO", status: "Done", priority: "Low", due: "", lastActivity: "2026-03-02", daysInStatus: 1, url: "https://trello.com/c/87OUbnpT" },
    { name: "SEO-014: SERP Analyzer service built", project: "SEO", status: "Done", priority: "Low", due: "", lastActivity: "2026-03-02", daysInStatus: 1, url: "https://trello.com/c/ff1p6LyM" },
    { name: "LOE SITE-007: Contact form backend (/api/contact via MailerLite)", project: "LOE", status: "Done", priority: "Low", due: "", lastActivity: "2026-03-02", daysInStatus: 1, url: "https://trello.com/c/Bu90FBNF" },
    { name: "LOE SITE-008: MailerLite automation triggers configured via API", project: "LOE", status: "Done", priority: "Low", due: "", lastActivity: "2026-03-02", daysInStatus: 1, url: "https://trello.com/c/gKqTsrfW" },
  ],

  // ============================================================
  // FINANCIAL
  // ============================================================
  financial: [
    { date: "2026-03-01", project: "PROD-001 SEO Toolkit", category: "COGS", description: "DataForSEO — keyword/SERP data", amount: -40, recurring: true },
    { date: "2026-03-01", project: "PROD-001 SEO Toolkit", category: "COGS", description: "SE Ranking — rank tracking (Essential)", amount: -52, recurring: true },
    { date: "2026-03-01", project: "Global", category: "OpEx", description: "Domain: bookrocket.ai (annual ~$12)", amount: -1, recurring: true },
    { date: "2026-03-01", project: "Global", category: "OpEx", description: "Domain: loveoverexile.com (annual ~$15)", amount: -1.25, recurring: true },
    { date: "2026-03-01", project: "Global", category: "OpEx", description: "Anthropic / Claude Code", amount: -200, recurring: true },
    { date: "2026-03-01", project: "Global", category: "OpEx", description: "GitHub (Free tier)", amount: 0, recurring: true },
    { date: "2026-03-01", project: "Global", category: "OpEx", description: "Bitwarden", amount: -0.83, recurring: true },
    { date: "2026-03-01", project: "CLIENT-001 Love Over Exile", category: "COGS", description: "Vercel hosting (Free tier)", amount: 0, recurring: true },
    { date: "2026-03-01", project: "CLIENT-001 Love Over Exile", category: "COGS", description: "Google Analytics 4 (Free)", amount: 0, recurring: false },
    { date: "2026-03-01", project: "CLIENT-001 Love Over Exile", category: "COGS", description: "MailerLite (Free tier)", amount: 0, recurring: true },
  ],
};
